"""fdgdfg

Revision ID: c1788e7b065c
Revises: 1f12a5d93e1e
Create Date: 2023-11-06 02:11:44.380850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1788e7b065c'
down_revision: Union[str, None] = '1f12a5d93e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'phone_number',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.String(length=50),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=False)
    # ### end Alembic commands ###
